import type { CSSProperties } from "react";

/** Co-located styles for ProjectDocPicker. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  topRow: { display: "flex", alignItems: "flex-start", gap: 16 } satisfies CSSProperties,
  headerCol: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  searchCol: { flexShrink: 0, width: 240 } satisfies CSSProperties,
  list: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  row: (dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderBottom: "1px solid var(--border)",
    background: dragging ? "var(--bg-hover)" : "transparent",
    opacity: dragging ? 0.7 : 1,
  }),
  handle: (draggable: boolean): CSSProperties => ({
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: draggable ? "grab" : "default",
    visibility: draggable ? "visible" : "hidden",
    flexShrink: 0,
    background: "none",
    border: "none",
    padding: 0,
  }),
  moveBtns: { display: "flex", flexDirection: "column", gap: 0, flexShrink: 0 } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 2,
    color: "var(--text-muted)",
    cursor: disabled ? "default" : "pointer",
    opacity: disabled ? 0.35 : 1,
  }),
  pathCol: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 1 } satisfies CSSProperties,
  name: {
    fontSize: 14,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  dir: {
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  meta: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  truncated: { fontSize: 11, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
  previewBtn: {
    background: "none",
    border: "none",
    padding: 4,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "4px 2px",
  } satisfies CSSProperties,
  centerNote: { padding: "24px 12px", textAlign: "center", color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
