import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  rowHead: { display: "flex", alignItems: "stretch", gap: 0 } satisfies CSSProperties,
  rowMain: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    padding: "6px 10px",
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  titleLine: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  kindIcon: (color: string): CSSProperties => ({ color, flexShrink: 0 }),
  refs: { display: "flex", flexWrap: "wrap", gap: "0 12px" } satisfies CSSProperties,
  refLink: {
    background: "none",
    border: "none",
    padding: 0,
    lineHeight: 1.35,
    cursor: "pointer",
    overflowWrap: "anywhere",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    color: "var(--accent-text)",
    textAlign: "left",
  } satisfies CSSProperties,
  refText: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chevron: {
    display: "grid",
    placeItems: "center",
    padding: "0 8px",
    minWidth: 32,
    background: "none",
    border: "none",
    borderLeft: "1px solid var(--border)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  explanation: {
    padding: "8px 10px 10px",
    borderTop: "1px solid var(--border)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
} as const;
