import type { CSSProperties } from "react";

export const s = {
  page: { display: "flex", gap: 28, padding: "24px 28px 40px", alignItems: "flex-start" } satisfies CSSProperties,
  center: { padding: "24px 28px 28px" } satisfies CSSProperties,
  loadingStack: { padding: "24px 28px 28px", display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,

  header: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 6 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  title: { fontSize: 22, fontWeight: 700, color: "var(--text-primary)", margin: 0, flex: 1, minWidth: 220 } satisfies CSSProperties,
  accent: { color: "var(--accent-text)" } satisfies CSSProperties,
  subline: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  actions: { display: "flex", gap: 8 } satisfies CSSProperties,

  toc: { width: 200, flexShrink: 0, position: "sticky", top: 24, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  tocTitle: { fontSize: 11.5, fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  tocItem: (active: boolean): CSSProperties => ({
    textAlign: "left",
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 13,
    border: "none",
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    fontWeight: active ? 600 : 500,
  }),

  banner: (tone: "warn" | "info"): CSSProperties => ({
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
    border: "1px solid var(--border)",
    background: tone === "warn" ? "var(--crit-bg)" : "var(--bg-elevated)",
    color: "var(--text-primary)",
  }),
  bannerBody: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  bannerNext: { color: "var(--text-secondary)" } satisfies CSSProperties,

  card: (active: boolean): CSSProperties => ({
    border: `1px solid ${active ? "var(--accent)" : "var(--border)"}`,
    borderRadius: 10,
    background: "var(--bg-surface, var(--bg-elevated))",
    scrollMarginTop: 16,
  }),
  cardHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "14px 16px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 650,
    textAlign: "left",
  } satisfies CSSProperties,
  cardTitle: { flex: 1 } satisfies CSSProperties,
  cardBody: { padding: "0 16px 16px", display: "flex", flexDirection: "column", gap: 12, fontSize: 13.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  note: { fontSize: 12.5, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  bullets: { margin: 0, paddingLeft: 18, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  sublabel: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.04em" } satisfies CSSProperties,

  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 } satisfies CSSProperties,
  rowTop: { display: "flex", alignItems: "flex-start", gap: 10, minWidth: 0 } satisfies CSSProperties,
  rowText: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  path: { fontSize: 12.5, color: "var(--text-primary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", minWidth: 0 } satisfies CSSProperties,
  pathInline: { flex: 1, minWidth: 0, display: "flex", gap: 6, alignItems: "baseline" } satisfies CSSProperties,
  reason: { color: "var(--text-secondary)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" } satisfies CSSProperties,
  rationale: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  circle: { width: 22, height: 22, borderRadius: "50%", flexShrink: 0, display: "grid", placeItems: "center", fontSize: 12, fontWeight: 600, background: "var(--accent-bg)", color: "var(--accent-text)" } satisfies CSSProperties,
  pathRow: { display: "flex", alignItems: "center", gap: 10, minWidth: 0, padding: "8px 12px", borderRadius: 8, background: "var(--bg-elevated)" } satisfies CSSProperties,
  pathIcon: { flexShrink: 0, color: "var(--text-muted)" } satisfies CSSProperties,
  commandRow: { display: "flex", alignItems: "center", gap: 12, minWidth: 0, padding: "9px 12px", borderRadius: 8, border: "1px solid var(--border)", background: "var(--bg-primary)" } satisfies CSSProperties,
  commandIndex: { width: 12, flexShrink: 0, fontSize: 12, color: "var(--text-muted)", textAlign: "right" } satisfies CSSProperties,
  readingList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  command: { flex: 1, minWidth: 0, fontSize: 12.5, color: "var(--text-primary)", whiteSpace: "pre-wrap", overflowWrap: "anywhere" } satisfies CSSProperties,
  copyBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 4, borderRadius: 5, border: "none", background: "transparent", color: "var(--text-muted)", cursor: "pointer", flexShrink: 0 } satisfies CSSProperties,
  copiedLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 } satisfies CSSProperties,
  chip: { maxWidth: "100%", fontSize: 12, padding: "2px 8px", borderRadius: 5, border: "1px solid var(--border)", background: "var(--bg-hover)", color: "var(--accent-text)", cursor: "pointer", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  taskGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(max(200px, calc((100% - 24px) / 3)), 1fr))", gap: 12 } satisfies CSSProperties,
  taskCard: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 8, minWidth: 0, padding: "12px 14px", border: "1px solid var(--border)", borderRadius: 8, background: "var(--bg-elevated)" } satisfies CSSProperties,
  taskPath: { maxWidth: "100%", padding: 0, border: "none", background: "transparent", fontSize: 12, color: "var(--text-muted)", cursor: "pointer", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", textAlign: "left" } satisfies CSSProperties,
  taskTitle: { color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
} as const;
