import type { CSSProperties } from "react";

export const s = {
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "12px 16px",
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  main: { display: "flex", alignItems: "center", gap: 12, minWidth: 0 } satisfies CSSProperties,
  text: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 3 } satisfies CSSProperties,
  name: {
    fontFamily: "var(--font-mono, monospace)",
    fontWeight: 600,
    fontSize: 14,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  result: { fontSize: 12, color: "var(--text-secondary)", display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  target: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    maxWidth: "40%",
    minWidth: 0,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  path: {
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  category: { color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  actions: { display: "flex", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  errorToggle: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--warning, #d29922)",
    cursor: "pointer",
    fontSize: 12,
    textDecoration: "underline",
  } satisfies CSSProperties,
  errorLine: {
    fontSize: 12,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    paddingLeft: 30,
  } satisfies CSSProperties,
} as const;
